# Only baseline firewalls have per-instance identity overrides. A candidate
# creation gets a different sentinel, so fixed provider defaults cannot hide a
# recreation. Diagnostic IDs remain randomly generated by Terraform.
mock_provider "azapi" {}
mock_provider "azurerm" {
  mock_resource "azurerm_virtual_wan" {
    defaults = {
      id = "/subscriptions/00000000-0000-0000-0000-000000000001/resourceGroups/rg-firewall-graph/providers/Microsoft.Network/virtualWans/vwan"
    }
  }
  mock_resource "azurerm_virtual_hub" {
    defaults = {
      id = "/subscriptions/00000000-0000-0000-0000-000000000001/resourceGroups/rg-firewall-graph/providers/Microsoft.Network/virtualHubs/hub"
    }
  }
  mock_resource "azurerm_firewall" {
    defaults = {
      id = "/subscriptions/00000000-0000-0000-0000-000000000001/resourceGroups/rg-firewall-graph/providers/Microsoft.Network/azureFirewalls/UNEXPECTED-NEW-FIREWALL"
    }
  }
}
mock_provider "modtm" {}
mock_provider "random" {}

run "published_0_17_2" {
  command   = apply
  state_key = "firewall_upgrade"

  module {
    source = "./tests/unit/fixtures/firewall-graph/baseline"
  }

  override_resource {
    target = module.virtual_wan[0].module.firewalls.azurerm_firewall.fw["edge-east"]
    values = {
      id = "/subscriptions/00000000-0000-0000-0000-000000000001/resourceGroups/rg-firewall-graph/providers/Microsoft.Network/azureFirewalls/baseline-east"
    }
  }

  override_resource {
    target = module.virtual_wan[0].module.firewalls.azurerm_firewall.fw["edge-west"]
    values = {
      id = "/subscriptions/00000000-0000-0000-0000-000000000001/resourceGroups/rg-firewall-graph/providers/Microsoft.Network/azureFirewalls/baseline-west"
    }
  }

  assert {
    condition     = length(output.snapshot.firewall_resource_ids) == 2 && length(output.snapshot.diagnostic_settings_resource_ids) == 2
    error_message = "The real published baseline must create both keyed firewalls and both diagnostic settings."
  }

  assert {
    condition     = output.snapshot.firewall_resource_ids["edge-east"] != output.snapshot.firewall_resource_ids["edge-west"]
    error_message = "The baseline must have distinct per-key identities, different from the candidate creation sentinel."
  }
}

run "upgrade_plan" {
  command   = plan
  state_key = "firewall_upgrade"

  module {
    source = "./tests/unit/fixtures/firewall-graph/candidate"
  }

  assert {
    condition     = output.snapshot == run.published_0_17_2.snapshot
    error_message = "The upgrade plan must retain all legacy output values and types, including firewall and diagnostic IDs."
  }
}

run "upgrade_apply" {
  command   = apply
  state_key = "firewall_upgrade"

  module {
    source = "./tests/unit/fixtures/firewall-graph/candidate"
  }

  assert {
    condition     = output.snapshot == run.published_0_17_2.snapshot
    error_message = "Applying the upgrade must preserve both firewall identities, diagnostic identities, IP outputs and hub ownership."
  }
}

run "idempotent_plan" {
  command   = plan
  state_key = "firewall_upgrade"

  module {
    source = "./tests/unit/fixtures/firewall-graph/candidate"
  }

  assert {
    condition     = output.snapshot == run.published_0_17_2.snapshot
    error_message = "The second candidate plan must retain every published output."
  }
}

run "remove_one_firewall" {
  command   = apply
  state_key = "firewall_upgrade"

  module {
    source = "./tests/unit/fixtures/firewall-graph/candidate"
  }

  variables {
    configuration = {
      firewall_keys = ["edge-west"]
    }
  }

  assert {
    condition = (
      keys(output.snapshot.firewall_resource_ids) == ["edge-west"] &&
      output.snapshot.firewall_resource_ids["edge-west"] == run.published_0_17_2.snapshot.firewall_resource_ids["edge-west"] &&
      output.snapshot.diagnostic_settings_resource_ids["edge-west-audit"] == run.published_0_17_2.snapshot.diagnostic_settings_resource_ids["edge-west-audit"]
    )
    error_message = "Removing one firewall must remove only that firewall and its diagnostics, without replacing the other key."
  }
}

run "disable_firewalls" {
  command   = apply
  state_key = "firewall_upgrade"

  module {
    source = "./tests/unit/fixtures/firewall-graph/candidate"
  }

  variables {
    configuration = {
      firewall_keys = []
    }
  }

  assert {
    condition     = length(output.snapshot.firewall_resource_ids) == 0 && length(output.snapshot.diagnostic_settings_resource_ids) == 0
    error_message = "The mode guard must allow ordinary firewall and diagnostic removal."
  }
}

run "zero_deployed_hubs" {
  command   = apply
  state_key = "firewall_upgrade"

  module {
    source = "./tests/unit/fixtures/firewall-graph/candidate"
  }

  variables {
    configuration = {
      hub_keys = []
    }
  }

  assert {
    condition     = output.snapshot == null && length(module.virtual_wan) == 0
    error_message = "Disabling all hubs must remove module.virtual_wan[0], including mode markers."
  }
}
